##########################################################################
# @file prj.conf
# @brief Example MIDI1.0 Zepyr application
# @note
#
# @author Jan-Willem Smaal <usenet@gispen.org
# @date 20251220
##########################################################################
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=0

# Let's disable the boot banner because
# on the FRDM_MCXC242 overlay we use it will go out 
# the MIDI1.0 DIN port...
CONFIG_BOOT_BANNER=y

# We require serial port support with IRQ on RX.
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_MIDI1_SERIAL=y

##########################################################################
# Tune these settings to reduce the RAM footprint
##########################################################################
CONFIG_IDLE_STACK_SIZE=128
CONFIG_ISR_STACK_SIZE=1024

# EOF
