# SPDX-License-Identifier: Apache-2.0

# MIDI 1.0 Arpeggiator Application
CONFIG_LOG=y
CONFIG_BOOT_BANNER=y

# Driver support
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_MIDI1_SERIAL=y
CONFIG_MIDI1_CLOCK_CNTR=y
CONFIG_MIDI1_HARMONIC=y
CONFIG_COUNTER=y

# Require larger buffers for handling inputs and outputs concurrently
CONFIG_MIDI1_SERIAL_TX_BUF_SIZE=128

# Footprint settings
CONFIG_IDLE_STACK_SIZE=256
CONFIG_ISR_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=1024
