# SPDX-License-Identifier: Apache-2.0

# MIDI 1.0 Hybrid Test Application
CONFIG_LOG=y
CONFIG_BOOT_BANNER=y

# Driver support
CONFIG_MIDI1_SERIAL=y
CONFIG_MIDI1_CLOCK_CNTR=y

# TX Buffer size for the hybrid driver
CONFIG_MIDI1_SERIAL_TX_BUF_SIZE=128

# Footprint settings
CONFIG_IDLE_STACK_SIZE=256
CONFIG_ISR_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_MIDI1_HARMONIC=y
